CREATE TABLE IF NOT EXISTS courses (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS departments (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
) ENGINE=InnoDB;
ALTER TABLE students ADD COLUMN IF NOT EXISTS course_id BIGINT UNSIGNED NULL;
ALTER TABLE teachers ADD COLUMN IF NOT EXISTS department_id BIGINT UNSIGNED NULL;
INSERT INTO courses (name) SELECT DISTINCT TRIM(course) FROM students WHERE TRIM(course) <> ''
ON DUPLICATE KEY UPDATE name=VALUES(name);
UPDATE students s JOIN courses c ON c.name=TRIM(s.course) SET s.course_id=c.id WHERE s.course_id IS NULL;
